version: "3.7"
services:
  jaeger-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: "jaeger-es-ctn"
    restart: on-failure
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.23
    container_name: "jaeger-collector-ctn"
    restart: on-failure
    ports:
      - "14250" # grpc port, used by jaeger-agent to send spans in model.proto format
      - 14269:14269 # admin port: health check at / and metrics at /metrics
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://jaeger-es:9200
    depends_on:
      - jaeger-es

  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.23
    container_name: "jaeger-agent-ctn"
    restart: on-failure
    ports:
      - 6831:6831/udp # accept jaeger.thrift in compact Thrift protocol used by most current Jaeger clients
      - 5778:5778/tcp # serve configs, sampling strategies
      - 14271:14271 # admin port: health check at / and metrics at /metrics
    command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
    depends_on:
      - jaeger-collector

  jaeger-query:
    image: jaegertracing/jaeger-query:1.23
    container_name: "jaeger-query-ctn"
    restart: on-failure
    ports:
      - 16686:16686 # /api/* endpoints and Jaeger UI at /
      - 16687:16687 # admin port: health check at / and metrics at /metrics
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://jaeger-es:9200
    depends_on:
      - jaeger-collector
